version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_project
    restart: always
    env_file: .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
